### PR TITLE
Added supported modes for X3000i

### PR DESCRIPTION
**Pull request by c1em3ntchua**

### CODE REVIEW

**Comment by rrooggiieerr** [comment]
@c1em3ntchua , Thanks for your addition!

I have now documented the working of the CLI examine command in the readme:

### Detecting your projector capabilities
The benqprojector CLI can detect the commands, sources and modes your
projector supports. If you like to have your projector fully supported by this
Python library please run this command and create an issue on Github with the
output attached.

To examine your projector capabilities: `python3 -m benqprojector <serial port> <baud> examine`


If you have used this method, great! Otherwise would you be able to run this command and validate the output with your change?

**Comment by c1em3ntchua** [comment]
@rrooggiieerr I'm not able to run it yet as it's giving me the "Unexpected response".

---
C:\benqprojector.py-main>python3 -m benqprojector com4 115200 examine
No command echo received
Response: *modelname=x3000i#
Unexpected response: []
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\benqprojector.py-main\benqprojector\__main__.py", line 35, in <module>
    if not projector.connect():
  File "C:\benqprojector.py-main\benqprojector\benqprojector.py", line 134, in connect
    assert model is not None, "Failed to retrieve projector model"
AssertionError: Failed to retrieve projector model
---

**Comment by rrooggiieerr** [comment]
@c1em3ntchua interesting, `*modelname=x3000i#` should be a valid response. Could you try the same command with `--debug` as an extra argument, thus `python3 -m benqprojector com4 115200 examine --debug`

**Comment by rrooggiieerr** [comment]
@c1em3ntchua ok, thanks. It looks like your projector does not echo the command first before responding, unlike my projector. Hence the _No command echo received_ message. I will make the library a bit less strict and make it not fail on a missing command echo.

**Comment by c1em3ntchua** [comment]
@rrooggiieerr it worked this time! Here is the log:

Command macaddr=? not supported
Device com4 available
Command *ltim2=?# unsupported item
Command *bc=?# unsupported item
Command *color=?# unsupported item
Command *mute=?# blocked item
Command *vol=?# blocked item
Model: x3000i
Detecting supported commands
Command 3d supported
Command *amxdd=?# unsupported item
Command appmod supported
Command asp supported
Command *audiosour=?# unsupported item
Command *autopower=?# unsupported item
Command baud supported
Command *bc=?# unsupported item
Command blank supported
Command bri supported
Command *broadcasting=?# unsupported item
Command *color=?# unsupported item
Command con supported
Command ct supported
Command directpower supported
Command *freeze=?# unsupported item
Command highaltitude supported
Command *ins=?# unsupported item
Command lampm supported
Command *lpsaver=?# unsupported item
Command ltim supported
Command *ltim2=?# unsupported item
Command *macaddr=?# unsupported item
Command menu supported
Command *micvol=?# unsupported item
Command modelname supported
Command *mute=?# blocked item
Command pow supported
Command pp supported
Command *prjlogincode=?# unsupported item
Command qas supported
Command *rr=?# unsupported item
Command sharp supported
Command sour supported
Command *standbymic=?# unsupported item
Command *standbymnt=?# unsupported item
Command *standbynet=?# unsupported item
Command *vol=?# blocked item
Detecting supported video sources
Current mode for sour: smartsystem
Command *sour=dp# unsupported item
Command *sour=dvia# unsupported item
Command *sour=dvid# unsupported item
Command *sour=hdbaset# unsupported item
More than 5 empty responses
More than 5 empty responses
Command *sour=network# unsupported item
Command *sour=rgb# unsupported item
Command *sour=rgb2# unsupported item
Command *sour=rgb3# unsupported item
Command *sour=svid# unsupported item
Unexpected response format, response: #
Command *sour=usbreader# unsupported item
Command *sour=vid# unsupported item
Command *sour=wireless# unsupported item
Command *sour=ypbr# unsupported item
Command *sour=ypbr2# unsupported item
More than 5 empty responses
Detecting supported audio sources
Detecting supported picture modes
Command *appmod=?# blocked item
Current mode for appmod: None
Detecting supported color temperatures
Current mode for ct: normal
Command *ct=warmer# unsupported item
More than 5 empty responses
More than 5 empty responses
More than 5 empty responses
Command *ct=cooler# unsupported item
Command *ct=native# unsupported item
More than 5 empty responses
Detecting supported aspec ratios
Current mode for asp: 16:9
More than 5 empty responses
Command *asp=16:6# unsupported item
More than 5 empty responses
Command *asp=16:10# unsupported item
More than 5 empty responses
Command *asp=real# unsupported item
Command *asp=lbox# unsupported item
Command *asp=wide# unsupported item
Command *asp=anam# unsupported item
More than 5 empty responses
Detecting supported projector positions
Current mode for pp: ft
More than 5 empty responses
More than 5 empty responses
More than 5 empty responses
More than 5 empty responses
More than 5 empty responses
Detecting supported lamp modes
Current mode for lampm: seco
More than 5 empty responses
More than 5 empty responses
More than 5 empty responses
Command *lampm=seco2# unsupported item
Command *lampm=seco3# unsupported item
Command *lampm=dimming# unsupported item
More than 5 empty responses
Command *lampm=dualbr# unsupported item
Command *lampm=dualre# unsupported item
Command *lampm=single# unsupported item
Unexpected response format, response: #
More than 5 empty responses
Detecting supported 3d modes
Current mode for 3d: off
More than 5 empty responses
Command *3d=auto# blocked item
Command *3d=tb# blocked item
Command *3d=fs# blocked item
Command *3d=fp# blocked item
Command *3d=sbs# blocked item
Command *3d=da# blocked item
Command *3d=iv# blocked item
Command *3d=2d3d# unsupported item
Command *3d=nvidia# unsupported item
Command *3d=off# blocked item
Supported commands: ['3d', 'appmod', 'asp', 'baud', 'blank', 'bri', 'con', 'ct', 'directpower', 'highaltitude', 'lampm', 'ltim', 'menu', 'modelname', 'pow', 'pp', 'qas', 'sharp', 'sour']
Supported video sources: []
Supported audio sources: []
Supported picture modes: []
Supported color temperatures: []
Supported aspect ratios: []
Supported projector positions: []
Supported lamp modes: []
Supported 3D modes: []

**Comment by rrooggiieerr** [comment]
@c1em3ntchua ok, that's something! Is your projector on? Because it has to to be able to detect most settings. I have to add that to the documentation

**Comment by c1em3ntchua** [comment]
@rrooggiieerr yup it is on, but I'm running on the QS01 right now so some settings show blocked item. I note from [this manual](https://esupportdownload.benq.com/esupport/Projector/Control%20Protocols/PU9530/RS232%20Control%20Guide_0_Windows7_Windows8_WinXP.pdf) (page 8) that 

> If a command with correct format cannot be executed under certain condition, it will echo Block item.

Perhaps you could include the config as supported if it is "blocked".

**Comment by rrooggiieerr** [comment]
FYI, this is the document that I based my implementation on:
https://esupportdownload.benq.com/esupport/Projector/Control%20Protocols/MH535/RS232%20Control%20Guide_0_Windows10_Windows7_Windows8.pdf

**Comment by c1em3ntchua** [comment]
@rrooggiieerr the lack of video sources is strange indeed. But thanks for all you've done so far!

**Comment by rrooggiieerr** [comment]
@c1em3ntchua New version of the library now handles blocked item as being supported

**Comment by c1em3ntchua** [comment]
@rrooggiieerr thanks for the very quick updates!

I ran the examine script again. This time it gets stuck during detection of picture modes.

I noticed one of the comma
[benq_x3000i_log.txt](https://github.com/rrooggiieerr/benqprojector.py/files/10149781/benq_x3000i_log.txt)
nds was causing my projector display the source select screen. I managed to replicate it by sending a `*sour=hdmi#` throught Tera Term. For the record, I don't have HDMI1 plugged in. I don't think it causes any issues though.

I've attached the log as a file to avoid cluttering up the chat. Off to work for now.

**Comment by c1em3ntchua** [comment]
Strange. I just ran it again and this time it errors out at a different place.

Truncated log:
[benq_x3000i_log_2.txt](https://github.com/rrooggiieerr/benqprojector.py/files/10149784/benq_x3000i_log_2.txt)

**Comment by rrooggiieerr** [comment]
@c1em3ntchua I released an other test version of the library, could you give that one a try?

`pip install 'benqprojector==0.0.6.1'`

**Comment by c1em3ntchua** [comment]
@rrooggiieerr version 0.0.6.1 seems to handle unexpected responses a lot better. I tried a few different values of `_SERIAL_TIMEOUT` - 0.5, 0.1 and the original 0.05. I can't say which works best.

All three timeouts produced the same list of support commands, which is good. I'm getting the most picture modes out of 0.5 (4 modes), followed by 0.05 then 0.1. Interestingly, 0.1 produces the most "correct" list of 3D modes. Video, color temp, aspect ratios, projector positions and lamp modes are still missing. I suspect the script is expecting some sort of response after the initial echo.

`_SERIAL_TIMEOUT = 0.5`
[benq_x3000i_log_timeout_0.5.txt](https://github.com/rrooggiieerr/benqprojector.py/files/10154894/benq_x3000i_log_timeout_0.5.txt)

`_SERIAL_TIMEOUT = 0.1`
[benq_x3000i_log_timeout_0.1.txt](https://github.com/rrooggiieerr/benqprojector.py/files/10154896/benq_x3000i_log_timeout_0.1.txt)

`_SERIAL_TIMEOUT = 0.05`
[benq_x3000i_log_timeout_0.05.txt](https://github.com/rrooggiieerr/benqprojector.py/files/10154900/benq_x3000i_log_timeout_0.05.txt)

**Comment by c1em3ntchua** [comment]
@rrooggiieerr, thanks for your reply.

This is the Tera Term input/output. The commands are in lower case while the responses are in upper case. For my case, I start with HDMI2 and call HDMI1 `*sour=hdmi#`. As I do not have a source connected to HDMI1, it brings up the source selection screen. Calling HDMI3 `*sour=smartsystem#` does change the source to the internal QS01 Android TV stick.

image

Let me try tweaking the values in `benqprojector.py` and run the examine code again. 

Thanks!

**Comment by rrooggiieerr** [comment]
@c1em3ntchua I think I'm onto something, give me a minute to make a modification and push to Github

**Comment by rrooggiieerr** [comment]
@c1em3ntchua I now detect if a command echo is expected by the projector, please use the latest version of the Github code

**Comment by c1em3ntchua** [comment]
@rrooggiieerr I believe you are really close! 

Picture modes and colour temps are still missing with a timeout of 0.05:
2022-12-05 23:32:25,366 INFO     Supported commands: ['3d', 'appmod', 'asp', 'baud', 'blank', 'bri', 'con', 'ct', 'directpower', 'highaltitude', 'lampm', 'ltim', 'menu', 'modelname', 'mute', 'pow', 'pp', 'qas', 'sharp', 'sour', 'vol']
2022-12-05 23:32:25,366 INFO     Supported video sources: ['hdmi', 'hdmi2']
2022-12-05 23:32:25,366 INFO     Supported audio sources: []
2022-12-05 23:32:25,367 INFO     Supported picture modes: []
2022-12-05 23:32:25,367 INFO     Supported color temperatures: []
2022-12-05 23:32:25,368 INFO     Supported aspect ratios: ['4:3', '16:9', 'auto']
2022-12-05 23:32:25,368 INFO     Supported projector positions: ['ft', 're', 'rc', 'fc']
2022-12-05 23:32:25,369 INFO     Supported lamp modes: ['lnor', 'eco', 'seco', 'custom']
2022-12-05 23:32:25,370 INFO     Supported 3D modes: ['off', 'auto', 'tb', 'fs', 'fp', 'sbs', 'da', 'iv']

Timeout of 0.5 produces this:
2022-12-05 23:46:22,853 INFO     Supported commands: ['3d', 'appmod', 'asp', 'baud', 'blank', 'bri', 'con', 'ct', 'directpower', 'highaltitude', 'lampm', 'ltim', 'menu', 'modelname', 'mute', 'pow', 'pp', 'qas', 'sharp', 'sour', 'vol']
2022-12-05 23:46:22,853 INFO     Supported video sources: ['hdmi', 'hdmi2']
2022-12-05 23:46:22,854 INFO     Supported audio sources: []
2022-12-05 23:46:22,854 INFO     Supported picture modes: []
2022-12-05 23:46:22,854 INFO     Supported color temperatures: ['warm', 'normal', 'cool']
2022-12-05 23:46:22,855 INFO     Supported aspect ratios: ['4:3', '16:9', 'auto']
2022-12-05 23:46:22,855 INFO     Supported projector positions: ['ft', 're', 'rc', 'fc']
2022-12-05 23:46:22,855 INFO     Supported lamp modes: ['lnor', 'eco', 'seco', 'custom']
2022-12-05 23:46:22,855 INFO     Supported 3D modes: ['off', 'auto', 'tb', 'fs', 'fp', 'sbs', 'da', 'iv']

I seem to be getting unexpected responses for longer commands. Let me see if I can tweak timings for these:
2022-12-05 23:45:28,121 DEBUG    command *sour=usbdisplay#
2022-12-05 23:45:28,426 DEBUG    Response: #
2022-12-05 23:45:28,428 DEBUG    Raw response: '#'
2022-12-05 23:45:28,455 ERROR    Unexpected response format, response: #
2022-12-05 23:45:32,436 DEBUG    command *sour=smartsystem#
2022-12-05 23:45:32,452 DEBUG    Response: m
2022-12-05 23:45:32,453 DEBUG    Raw response: 'm'
2022-12-05 23:45:32,453 ERROR    Unexpected response format, response: m
2022-12-05 23:46:11,604 DEBUG    command *lampm=singleeco#
2022-12-05 23:46:11,620 DEBUG    Response: #
2022-12-05 23:46:11,621 DEBUG    Raw response: '#'
2022-12-05 23:46:11,621 ERROR    Unexpected response format, response: #

**Comment by rrooggiieerr** [comment]
You can also move the detection of picture modes to earlier in the code

**Comment by c1em3ntchua** [comment]
Almost there. This is the output with the default timings. Only change I made was to place `projector.detect_video_sources()` at the end. I seem to have almost everything now. The only things that are missing are the video sources, some picture modes and modes that are not already present in `PROJECTOR_CONFIGS["all"]`.

Interestingly, I found out that native colour temperature is not supported in my projector. I confirmed it in my projector's settings. The manual says otherwise lol.

2022-12-06 00:09:23,399 INFO     Supported commands: ['3d', 'appmod', 'asp', 'baud', 'blank', 'bri', 'con', 'ct', 'directpower', 'highaltitude', 'lampm', 'ltim', 'menu', 'modelname', 'mute', 'pow', 'pp', 'qas', 'sharp', 'sour', 'vol']
2022-12-06 00:09:23,402 INFO     Supported video sources: ['hdmi2']
2022-12-06 00:09:23,405 INFO     Supported audio sources: []
2022-12-06 00:09:23,406 INFO     Supported picture modes: ['game', 'cine', 'std', 'threed']
2022-12-06 00:09:23,406 INFO     Supported color temperatures: ['warm', 'normal', 'cool']
2022-12-06 00:09:23,406 INFO     Supported aspect ratios: ['4:3', '16:9', 'auto']
2022-12-06 00:09:23,407 INFO     Supported projector positions: ['ft', 're', 'rc', 'fc']
2022-12-06 00:09:23,407 INFO     Supported lamp modes: ['lnor', 'eco', 'seco', 'custom']
2022-12-06 00:09:23,408 INFO     Supported 3D modes: ['off', 'auto', 'tb', 'fs', 'fp', 'sbs', 'da', 'iv']

Let me put a `time.sleep(5)` just before the return statement of `def detect_video_sources(self)` and see if it works better.

**Comment by rrooggiieerr** [comment]
If you also take the latest version of config.py then at least smartsystem should be also detected

**Comment by c1em3ntchua** [comment]
Those modes that do not appear in the supported list seem to have an unexpected response to them. I'm not sure what's causing the unexpected response.

I have tried changing values mentioned in the below post but it hasn't worked reliably yet.

> @c1em3ntchua , That looks actually very promising!
> 
> If the code is detecting your input sources, is it actually switching to the source?
> 
> What happens if you send a command like `*sour=hdmi#` when using Tera Term? Does it immediately respond, or take long before you get a response? Maybe you only get a response when the source is actually switched?
> 
> In line 295 of `benqprojector.py` you can see I'm waiting for 1 timeout until I try to read the response again. After more than 5 failed response I give up (line 281). Since the readline also takes 1 timeout to timeout in the end the code waits about 10 timeouts before it gives up.
> 
> You could try to increase the number of times to try (line 279) to maybe 20 and give that a try.
> 
> An other thing you could try is wait longer between detecting modes. Currently I'm waiting for 0.2 seconds before I continue detecting the next mode (line 418). Maybe make it 5 seconds at first and then see which other values work
> 
> All the timings I used were based on what works with my model of projector, there are no specifications from BenQ which tell me how long to wait for everything. So it's a bit trail and error to find out the right settings and maintain a responsive communication with the projector.
> 
> Thanks for debugging my code ;-)

**Comment by rrooggiieerr** [comment]
I see you projector supports the `menu` command which mine doesn't. I'm guessing it shows the on screen menu and with the commands `*up#`, `*down#`,`*left#` and `*right#` you are able to navigate trough the menu.

Those commands are not yet supported, and I don't know it it adds anything to the implementation because a lot of parameters can be set directly without the need of the onscreen display

**Comment by c1em3ntchua** [comment]
Yes it does. It mostly controls the on screen menu which I don't think is required in HA. We can do away with those :)

Below should be the updated list of commands supported.

`    "x3000i": {
        "commands": [
             "3d",
             "appmod",
             "asp",
             "baud",
             "blank",
             "bri",
             "con",
             "ct",
             "directpower",
             "highaltitude",
             "hkeystone",
             "lampm",
             "ltim",
             "mcufwversion"
             "modelname",
             "mute",
             "pow",
             "pp",
             "qas",
             "scalerfwversion",
             "sharp",
             "sour",
             "sysfwversion",
             "vkeystone",
             "vol",
        ],
        "sources": ["hdmi", "hdmi2", "smartsystem"],
        "audio_sources": [],
        "picture_modes": ["bright", "livingroom", "game", "cine", "sport", "user1", "threed"],
        "color_temperatures": ["warm", "normal", "cool"], # manual says native is supported, but apparently not
        "aspect_ratios": ["4:3", "16:9", "2.4:1", "auto"],
        "projector_positions": ["ft", "re", "rc", "fc"],
        "menu_positions": ["center", "tl", "tr", "br", "bl"],
        "lamp_modes": ["lnor", "eco", "seco", "custom"],
        "3d_modes": ["off", "auto", "tb", "fs", "fp", "sbs", "da", "iv"], # sbs, tb, and fp were enabled with a firmware update but undocumented
        "poweron_time": 100,
        "poweroff_time": 100,
    }`

**Review by rrooggiieerr — APPROVED** [review]

**Comment by c1em3ntchua** [comment]
@rrooggiieerr thank you so much for taking the time to debug the settings. Appreciate it!

**Comment by rrooggiieerr** [comment]
New HA integration available. FYI, you can also add the repository as a custom one to HACS (see instructions) so future updates can be easily installed

**Pull request merged**
