### PR TITLE
Update x3000i.json

### PR DESCRIPTION
**Pull request by c1em3ntchua**
Additional commands and power times.

### CODE REVIEW

**Comment by rrooggiieerr** [comment]
Hi @c1em3ntchua, thanks for your updates on the supported commands for the x3000i!

To make the new commands also supported by the projector capabilities test of the library they also need to be added to the `all.json`, and some changes in the code need to be made.

To have the commands supported by the HA integration some changes also need to be made there.

Maybe you could have a look at that too?

**Comment by rrooggiieerr** [comment]
@c1em3ntchua, I'm having a problem with the menu position. According to your json the options are `center`, `tl`, `tr`, `br`, `bl`, however on my projector `center` is `cen`. Can you validate that your options are correct?

**Comment by c1em3ntchua** [comment]
Hi @rrooggiieerr, I can indeed confirm that my projector uses `center` for `menuposition`. See attached log.
[x3000i.txt](https://github.com/rrooggiieerr/benqprojector.py/files/13746783/x3000i.txt)

I'll see about the additional commands. Currently I do not have any use for them, but I thought to include them after running the examine script in case someone else finds them useful in the future.

**Comment by rrooggiieerr** [comment]
Ok, thanks. That means we need to support both `cen` and `center`. I love how inconsistent these BenQ projectors are between models. Not. I actually already made the necessary changes in the library and am now working on adding it to the HA integration. If you could give it a good test that would be great, because testing actually takes more time than the actual coding.

**Comment by c1em3ntchua** [comment]
I don't think supporting both `cen` and `center` would be a problem. The library would see it as just another compatible/unsupported command. But sure, I could try to test it on my end.

**Comment by rrooggiieerr** [comment]
I agree, and that's how I have implemented it now

**Comment by rrooggiieerr** [comment]
My projector does not support the `hdrbri` command. Could you tell me if it's a numeric format and what the min and max values are?

**Comment by c1em3ntchua** [comment]
Yes, it is a numeric format from -2 to +2.

**Pull request merged**
