### PR TITLE
[+] benqprojector/benqprojector.py - fixed telnet network support (te…

### PR DESCRIPTION
**Pull request by yellow1234**
fixed telnet network support

i tried the home assistant integration and got "connection failed error"
than tried that module which also didnt work

so i fixed that my self and its not now working

its tested on w4000i/ht4550i

thanks

### CODE REVIEW

**Comment by rrooggiieerr** [comment]
THanks for getting involved! I just updated the library to be asynchronous so you might want to try the new library first. Also I don't see what you're trying to solve. '*' is part of the response message, not any whitespace or control characters. Is your model not returning any newlines or carriage return at the end of the response?

Are you using a RS232 to WiFi bridge or the network connection of your projector?

**Comment by yellow1234** [comment]
> THanks for getting involved! I just updated the library to be asynchronous so you might want to try the new library first. Also I don't see what you're trying to solve. '*' is part of the response message, not any whitespace or control characters. Is your model not returning any newlines or carriage return at the end of the response?
> 
> Are you using a RS232 to WiFi bridge or the network connection of your projector?

For sure i know "*" is part of the response

But over network projector directly there is no any response "sign" for the response like
\n
\r
>

Its only the response msg directly
 So after the command is sent i just skipping to getting the reply and not waiting for whitespace or control characters

And yes, im not over RS232 to WiFi bridge
Its over the lan directly with ethernet

Thanks

**Comment by rrooggiieerr** [comment]
Interesting. I think you're the first one who is actually using the native network connection instead of a serial to WiFi bridge. I'd like to understand this a bit better.

If you telnet to the projector and send commands, how does it behave? Is it all just in a continuous stream or are there different lines for the command and response?

**Comment by rrooggiieerr** [comment]
Just some follow up questions:

Is the port number indeed 8000 to communicate with the projector?

It would be interesting to implement auto discovery, does the device support [SSDP](https://en.wikipedia.org/wiki/Simple_Service_Discovery_Protocol)?

Otherwise DHCP discovery would be possible, for this the projector would have to use a mac address that's linked to the manyfacturer (BenQ) or use a default hostname `<something>.local`.
Would you know the mac address and hostname of your device?

**Comment by rrooggiieerr** [comment]
Getting back to your solution, I think it would make more sense to trigger on the `#`, since that is the end of the response message, and I also think it would work on the serial connected and serial to WiFi connected devices and thus be a more generic solution, not needing any of the `is_network` checks.

**Comment by yellow1234** [comment]
> Interesting. I think you're the first one who is actually using the native network connection instead of a serial to WiFi bridge. I'd like to understand this a bit better.
> 
> If you telnet to the projector and send commands, how does it behave? Is it all just in a continuous stream or are there different lines for the command and response?

Yes exactly
Its all just in a continuous stream

nothing else

first i tried telnet via putty and saw that if i write
<<<
enter
*pow=?#
enter
<<<

its working and im getting response
than i started debug manually your project and saw where its fail

**Comment by yellow1234** [comment]
> Just some follow up questions:
> 
> Is the port number indeed 8000 to communicate with the projector?
> 
> It would be interesting to implement auto discovery, does the device support [SSDP](https://en.wikipedia.org/wiki/Simple_Service_Discovery_Protocol) or [Zeroconf](https://en.wikipedia.org/wiki/Zero-configuration_networking)?
> 
> Otherwise DHCP discovery would be possible, for this the projector would have to use a mac address that's linked to the manyfacturer (BenQ) or use a default hostname `<something>.local`. Would you know the mac address and hostname of your device?

Yes its on port 8000

About the auto discovery im not sure
I did static ip for the projector mac addr on my asus router

**Comment by yellow1234** [comment]
> Getting back to your solution, I think it would make more sense to trigger on the `#`, since that is the end of the response message, and I also think it would work on the serial connected and serial to WiFi connected devices and thus be a more generic solution, not needing any of the `is_network` checks.

Of course you know better than me whats working for the serial port and be more generic
I dont have serial the check how its working
I just tried to find a simple and fast solution for my issue

**Comment by rrooggiieerr** [comment]
Could you give the latest GitHub code a try?

**Comment by yellow1234** [comment]
> Could you give the latest GitHub code a try?

I'll try later this week
Im not near the projector for a few days

But from what I saw fastly
The new changes just moved everything to be async
No something that would make change

But i'll try yes

**Comment by rrooggiieerr** [comment]
> The new changes just moved everything to be async

Actually, it also accepts `#` as end of response, which is what should solve your problem

https://github.com/rrooggiieerr/benqprojector.py/blob/20dcdd37be6414f38216f37681f08397209fa771/benqprojector/benqprojector.py#L37C1-L37C31

**Comment by rrooggiieerr** [comment]
@yellow1234, is the latest version working for you now?

**Comment by omelettedufromagee** [comment]
Using 0.1.2, I'm still having issues:

> python -m benqprojector telnet 192.168.86.234 8000 status --debug
2024-10-25 20:27:32,670 DEBUG    proactor_events.py:631 Using proactor: IocpProactor
2024-10-25 20:27:32,671 DEBUG    proactor_events.py:631 Using proactor: IocpProactor
2024-10-25 20:27:32,672 INFO     benqprojector.py:305 Connecting to 192.168.86.234:8000
2024-10-25 20:27:32,673 DEBUG    benqprojector.py:307 Connected to 192.168.86.234:8000
2024-10-25 20:27:32,888 DEBUG    benqprojector.py:736 command *pow=?#
2024-10-25 20:27:33,103 DEBUG    benqprojector.py:726 Waiting for response
2024-10-25 20:27:33,374 DEBUG    benqprojector.py:726 Waiting for response
2024-10-25 20:27:33,644 DEBUG    benqprojector.py:726 Waiting for response
2024-10-25 20:27:33,906 DEBUG    benqprojector.py:726 Waiting for response
2024-10-25 20:27:34,172 DEBUG    benqprojector.py:726 Waiting for response
2024-10-25 20:27:34,436 DEBUG    benqprojector.py:726 Waiting for response
2024-10-25 20:27:34,712 DEBUG    benqprojector.py:726 Waiting for response
2024-10-25 20:27:34,976 DEBUG    benqprojector.py:726 Waiting for response
2024-10-25 20:27:35,239 DEBUG    benqprojector.py:726 Waiting for response
2024-10-25 20:27:35,515 DEBUG    benqprojector.py:726 Waiting for response
2024-10-25 20:27:35,779 DEBUG    benqprojector.py:726 Waiting for response
2024-10-25 20:27:36,044 DEBUG    benqprojector.py:726 Waiting for response
2024-10-25 20:27:36,310 DEBUG    benqprojector.py:726 Waiting for response
2024-10-25 20:27:36,572 DEBUG    benqprojector.py:726 Waiting for response
2024-10-25 20:27:36,834 DEBUG    benqprojector.py:726 Waiting for response
2024-10-25 20:27:37,099 DEBUG    benqprojector.py:726 Waiting for response
2024-10-25 20:27:37,362 DEBUG    benqprojector.py:726 Waiting for response
2024-10-25 20:27:37,627 DEBUG    benqprojector.py:726 Waiting for response
2024-10-25 20:27:37,892 WARNING  benqprojector.py:722 Timeout while waiting for response
2024-10-25 20:27:37,893 ERROR    benqprojector.py:356 Unable to retrieve projector power state: Response timeout for command 'pow' and action '?'
2024-10-25 20:27:37,894 ERROR    __main__.py:32 Failed to connect to BenQ projector

**Comment by omelettedufromagee** [comment]
In _read_response, I replace the readline call since there is no CR
`_response = await self.connection.readline()`
by 
`_response = await self.connection.read(100)`

It's working properly now.

**Comment by rrooggiieerr** [comment]
Ok, good point about `readline` vs `read`. Would that have impact on the performance? I think `read` it will wait for the read_timeout to expire while `readline` will return once `\n` has ben found.

I think `readuntil` would be a better candidate. https://docs.python.org/3/library/asyncio-stream.html#asyncio.StreamReader.readuntil

I need to create a wrapper around that in the `BenQConnection` class and do some testing on that later

**Comment by omelettedufromagee** [comment]
Since I use read(100), it's reading directly 100 bytes. Most responses are actually like 10 bytes long so it could be reduced. However, I am getting immediate results, see below:

> python -m benqprojector telnet 192.168.86.234 8000 status --debug
2024-10-25 21:28:14,431 DEBUG    proactor_events.py:631 Using proactor: IocpProactor
2024-10-25 21:28:14,432 DEBUG    proactor_events.py:631 Using proactor: IocpProactor
2024-10-25 21:28:14,433 INFO     benqprojector.py:305 Connecting to 192.168.86.234:8000
2024-10-25 21:28:14,435 DEBUG    benqprojector.py:307 Connected to 192.168.86.234:8000
2024-10-25 21:28:14,658 DEBUG    benqprojector.py:671 No prompt detected
2024-10-25 21:28:14,658 DEBUG    benqprojector.py:736 command *pow=?#
2024-10-25 21:28:14,794 DEBUG    benqprojector.py:716 Response: *POW=OFF#
2024-10-25 21:28:14,795 WARNING  benqprojector.py:641 No command echo received
2024-10-25 21:28:14,795 DEBUG    benqprojector.py:767 Processed response: off
2024-10-25 21:28:14,796 DEBUG    benqprojector.py:736 command *modelname=?#
2024-10-25 21:28:14,837 DEBUG    benqprojector.py:716 Response: *MODELNAME=W4000i#
2024-10-25 21:28:14,837 DEBUG    benqprojector.py:767 Processed response: w4000i
2024-10-25 21:28:14,848 DEBUG    benqprojector.py:736 command *macaddr=?#
2024-10-25 21:28:14,859 DEBUG    benqprojector.py:716 Response: *Block Item#
2024-10-25 21:28:14,860 WARNING  benqprojector.py:755 Command *macaddr=?# blocked item
2024-10-25 21:28:14,860 INFO     benqprojector.py:410 Device on 192.168.86.234:8000 available
2024-10-25 21:28:14,861 DEBUG    benqprojector.py:736 command *pow=?#
2024-10-25 21:28:14,972 DEBUG    benqprojector.py:716 Response: *POW=OFF#
2024-10-25 21:28:14,972 DEBUG    benqprojector.py:767 Processed response: off
2024-10-25 21:28:14,973 DEBUG    benqprojector.py:736 command *pow=?#
2024-10-25 21:28:15,101 DEBUG    benqprojector.py:716 Response: *POW=OFF#
2024-10-25 21:28:15,102 DEBUG    benqprojector.py:767 Processed response: off
2024-10-25 21:28:15,103 DEBUG    benqprojector.py:736 command *directpower=?#
2024-10-25 21:28:15,166 DEBUG    benqprojector.py:716 Response: *Block Item#
2024-10-25 21:28:15,166 WARNING  benqprojector.py:755 Command *directpower=?# blocked item
2024-10-25 21:28:15,167 DEBUG    benqprojector.py:1142 Direct power on: False
2024-10-25 21:28:15,167 DEBUG    benqprojector.py:736 command *ltim=?#
2024-10-25 21:28:15,208 DEBUG    benqprojector.py:716 Response: *Block Item#
2024-10-25 21:28:15,209 WARNING  benqprojector.py:755 Command *ltim=?# blocked item
2024-10-25 21:28:15,210 DEBUG    benqprojector.py:736 command *ltim2=?#
2024-10-25 21:28:15,257 DEBUG    benqprojector.py:716 Response: *Block Item#
2024-10-25 21:28:15,258 WARNING  benqprojector.py:755 Command *ltim2=?# blocked item
2024-10-25 21:28:15,259 DEBUG    benqprojector.py:736 command *pp=?#
2024-10-25 21:28:15,279 DEBUG    benqprojector.py:716 Response: *Block Item#
2024-10-25 21:28:15,280 WARNING  benqprojector.py:755 Command *pp=?# blocked item
2024-10-25 21:28:15,281 INFO     __main__.py:39 Model: w4000i
2024-10-25 21:28:15,281 INFO     __main__.py:40 Position: None
2024-10-25 21:28:15,282 INFO     __main__.py:42 Power off
2024-10-25 21:28:15,282 INFO     __main__.py:46 Direct power on  : False
2024-10-25 21:28:15,282 INFO     __main__.py:52 Lamp time        : None hours
2024-10-25 21:28:15,283 INFO     __main__.py:72 Supported video sources: ['dp', 'dvia', 'dvid', 'hdbaset', 'hdmi', 'hdmi2', 'hdmi3', 'network', 'rgb', 'rgb2', 'rgb3', 'svid', 'usbdisplay', 'usbreader', 'vid', 'wireless', 'ypbr', 'ypbr2', 'smartsystem']
2024-10-25 21:28:15,284 INFO     __main__.py:101 Disconnecting from BenQ projector
2024-10-25 21:28:15,284 DEBUG    benqconnection.py:76 Connection closed

**Comment by rrooggiieerr** [comment]
Is that also the case when using a serial connection? The implementation uses a different library to communicate with serial connections (serial_asyncio_fast) than it does with networked connections (socket).

**Comment by rrooggiieerr** [comment]
@omelettedufromagee I made changes to the library which I think should work for native networked projectors and also work on serial and serial to network bridges (I tested both).

If you could confirm it works on your networked projector that would be great!

**Comment by omelettedufromagee** [comment]
@rrooggiieerr it's working worderfully!

> python -m benqprojector telnet 192.168.86.234 8000 status
Connecting to 192.168.86.234:8000
No command echo received
Device on 192.168.86.234:8000 available
Model: w4000i
Position: re
Power on
Direct power on  : False
Lamp time        : 141 hours
3D               : auto
Picture mode     : cine
Aspect ratio     : auto
Brilliant color  : None
Blank            : False
Brightness       : 50
Color value      : 50
Contrast         : 50
Color temperature: normal
High altitude    : False
Lamp mode        : seco
Quick auto search: False
Sharpness        : 12
Video Source     : hdmi
Volume           : 14
Muted            : False
Supported video sources: ['hdmi', 'hdmi2', 'hdmi3', 'usbreader']
Disconnecting from BenQ projector

I added the w4000i config file as well for the testing.

**Comment by rrooggiieerr** [comment]
Wonderfull! I'll be releasing a new version in the upcoming days then. Thanks for the feedback

**Comment by rrooggiieerr** [comment]
@omelettedufromagee I updated the HA integration to use the latest library, could you give that a try?

To install the latest main branch from GitHub run the following action form Developer tools > Actions:
```
action: update.install
target:
  entity_id: update.benq_projector_update
data:
  version: main
```

**Comment by omelettedufromagee** [comment]
It's working great. I had change the manifest manually yesterday to run some test.
I'll probably propose some changes later but it's more cosmetic than anything (like the HDR Brightness slider not going to -1 or -2).
image

**Pull request closed without merging**
